# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "pastel", "~> 0.8.0"
gem "rspec", "~> 3.10"
gem "tty-color", "~> 0.6.0"
gem "tty-cursor", "~> 0.7.1"
gem "tty-font", "~> 0.5.0"
gem "tty-prompt", "~> 0.23.0"
gem "tty-reader", "~> 0.9.0"
gem "tty-screen", "~> 0.8.1"
gem "tty-table", "~> 0.12.0"
gem "wisper", "~> 2.0"
